/* 
 *  Copyright (C) 2021-2025 mod.io Pty Ltd. <https://mod.io>
 *  
 *  This file is part of the mod.io SDK.
 *  
 *  Distributed under the MIT License. (See accompanying file LICENSE or 
 *   view online at <https://github.com/modio/modio-sdk/blob/main/LICENSE>)
 *  
 */

#pragma once
// Autogenerated file - do not edit directly!
// Should never be included directly - include ModioHttpParams.h instead

#include "modio/detail/ModioCompilerMacros.h"

MODIO_DISABLE_WARNING_PUSH 
MODIO_DISABLE_WARNING_L2R_EVALUATION_ORDER_OPERATOR
MODIO_DISABLE_WARNING_L2R_EVALUATION_ORDER_INITIALIZER

namespace Modio 
{
    namespace Detail
    {
        static const HttpRequestParams GetCurrentAgreementRequest { Modio::Detail::Verb::GET, "/agreements/types/{agreement-type-id}/current" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams GetAgreementVersionRequest { Modio::Detail::Verb::GET, "/agreements/versions/{agreement-version-id}" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams TermsRequest { Modio::Detail::Verb::GET, "/authenticate/terms" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams AuthenticateViaAppleRequest { Modio::Detail::Verb::POST, "/external/appleauth" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams AuthenticateViaDiscordRequest { Modio::Detail::Verb::POST, "/external/discordauth" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams AuthenticateViaEpicgamesRequest { Modio::Detail::Verb::POST, "/external/epicgamesauth" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams AuthenticateViaFacebookRequest { Modio::Detail::Verb::POST, "/external/facebookauth" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams AuthenticateViaGogGalaxyRequest { Modio::Detail::Verb::POST, "/external/galaxyauth" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams AuthenticateViaGoogleRequest { Modio::Detail::Verb::POST, "/external/googleauth" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams AuthenticateViaItchioRequest { Modio::Detail::Verb::POST, "/external/itchioauth" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams AuthenticateViaOculusRequest { Modio::Detail::Verb::POST, "/external/oculusauth" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams AuthenticateViaOpenidRequest { Modio::Detail::Verb::POST, "/external/openidauth" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams AuthenticateViaPsnRequest { Modio::Detail::Verb::POST, "/external/psnauth" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams AuthenticateViaSteamRequest { Modio::Detail::Verb::POST, "/external/steamauth" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams AuthenticateViaSwitchRequest { Modio::Detail::Verb::POST, "/external/switchauth" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams AuthenticateViaXboxLiveRequest { Modio::Detail::Verb::POST, "/external/xboxauth" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams GetGamesRequest { Modio::Detail::Verb::GET, "/games" }; 
        static const HttpRequestParams GetGameRequest { Modio::Detail::Verb::GET, "/games/{game-id}" }; 
        static const HttpRequestParams FinalizeCloudCookingRequest { Modio::Detail::Verb::POST, "/games/{game-id}/cloud-cooking/finalization" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams CloudCookingWebhookRequest { Modio::Detail::Verb::POST, "/games/{game-id}/cloud-cooking/webhook" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams GetModCollectionsRequest { Modio::Detail::Verb::GET, "/games/{game-id}/collections" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams AddCollectionRequest { Modio::Detail::Verb::POST, "/games/{game-id}/collections" , GetContentTypeEnum("multipart/form-data") }; 
        static const HttpRequestParams DeleteCollectionRequest { Modio::Detail::Verb::DELETE, "/games/{game-id}/collections/{collection-id}" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams GetModCollectionRequest { Modio::Detail::Verb::GET, "/games/{game-id}/collections/{collection-id}" }; 
        static const HttpRequestParams UpdateCollectionRequest { Modio::Detail::Verb::POST, "/games/{game-id}/collections/{collection-id}" , GetContentTypeEnum("multipart/form-data") }; 
        static const HttpRequestParams GetCollectionCommentsRequest { Modio::Detail::Verb::GET, "/games/{game-id}/collections/{collection-id}/comments" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams AddCollectionCommentRequest { Modio::Detail::Verb::POST, "/games/{game-id}/collections/{collection-id}/comments" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams DeleteCollectionCommentRequest { Modio::Detail::Verb::DELETE, "/games/{game-id}/collections/{collection-id}/comments/{comment-id}" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams GetCollectionCommentRequest { Modio::Detail::Verb::GET, "/games/{game-id}/collections/{collection-id}/comments/{comment-id}" }; 
        static const HttpRequestParams UpdateCollectionCommentRequest { Modio::Detail::Verb::PUT, "/games/{game-id}/collections/{collection-id}/comments/{comment-id}" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams AddCollectionCommentKarmaRequest { Modio::Detail::Verb::POST, "/games/{game-id}/collections/{collection-id}/comments/{comment-id}/karma" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams AddCollectionRatingRequest { Modio::Detail::Verb::POST, "/games/{game-id}/collections/{collection-id}/compatibility" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams UnfollowCollectionRequest { Modio::Detail::Verb::DELETE, "/games/{game-id}/collections/{collection-id}/followers" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams FollowCollectionRequest { Modio::Detail::Verb::POST, "/games/{game-id}/collections/{collection-id}/followers" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams DeleteCollectionModsRequest { Modio::Detail::Verb::DELETE, "/games/{game-id}/collections/{collection-id}/mods" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams GetCollectionModsRequest { Modio::Detail::Verb::GET, "/games/{game-id}/collections/{collection-id}/mods" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams UnsubscribeFromCollectionModsRequest { Modio::Detail::Verb::DELETE, "/games/{game-id}/collections/{collection-id}/subscriptions" }; 
        static const HttpRequestParams SubscribeToCollectionModsRequest { Modio::Detail::Verb::POST, "/games/{game-id}/collections/{collection-id}/subscriptions" }; 
        static const HttpRequestParams GetGuidesRequest { Modio::Detail::Verb::GET, "/games/{game-id}/guides" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams AddGuideRequest { Modio::Detail::Verb::POST, "/games/{game-id}/guides" , GetContentTypeEnum("multipart/form-data") }; 
        static const HttpRequestParams GetGuidesTagsRequest { Modio::Detail::Verb::GET, "/games/{game-id}/guides/tags" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams DeleteGuideRequest { Modio::Detail::Verb::DELETE, "/games/{game-id}/guides/{guide-id}" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams GetGuideRequest { Modio::Detail::Verb::GET, "/games/{game-id}/guides/{guide-id}" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams EditGuideRequest { Modio::Detail::Verb::POST, "/games/{game-id}/guides/{guide-id}" , GetContentTypeEnum("multipart/form-data") }; 
        static const HttpRequestParams GetGuideCommentsRequest { Modio::Detail::Verb::GET, "/games/{game-id}/guides/{guide-id}/comments" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams AddGuideCommentRequest { Modio::Detail::Verb::POST, "/games/{game-id}/guides/{guide-id}/comments" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams DeleteGuideCommentRequest { Modio::Detail::Verb::DELETE, "/games/{game-id}/guides/{guide-id}/comments/{comment-id}" }; 
        static const HttpRequestParams GetGuideCommentRequest { Modio::Detail::Verb::GET, "/games/{game-id}/guides/{guide-id}/comments/{comment-id}" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams UpdateGuideCommentRequest { Modio::Detail::Verb::PUT, "/games/{game-id}/guides/{guide-id}/comments/{comment-id}" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams AddGuideCommentKarmaRequest { Modio::Detail::Verb::POST, "/games/{game-id}/guides/{guide-id}/comments/{comment-id}/karma" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams AddGameMediaRequest { Modio::Detail::Verb::POST, "/games/{game-id}/media" , GetContentTypeEnum("multipart/form-data") }; 
        static const HttpRequestParams GetModsRequest { Modio::Detail::Verb::GET, "/games/{game-id}/mods" }; 
        static const HttpRequestParams AddModRequest { Modio::Detail::Verb::POST, "/games/{game-id}/mods" , GetContentTypeEnum("multipart/form-data") }; 
        static const HttpRequestParams GetModsEventsRequest { Modio::Detail::Verb::GET, "/games/{game-id}/mods/events" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams GetModsStatsRequest { Modio::Detail::Verb::GET, "/games/{game-id}/mods/stats" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams DeleteModRequest { Modio::Detail::Verb::DELETE, "/games/{game-id}/mods/{mod-id}" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams GetModRequest { Modio::Detail::Verb::GET, "/games/{game-id}/mods/{mod-id}" }; 
        static const HttpRequestParams EditModRequest { Modio::Detail::Verb::POST, "/games/{game-id}/mods/{mod-id}" , GetContentTypeEnum("multipart/form-data") }; 
        static const HttpRequestParams PurchaseRequest { Modio::Detail::Verb::POST, "/games/{game-id}/mods/{mod-id}/checkout" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams GetModCollectionsListRequest { Modio::Detail::Verb::GET, "/games/{game-id}/mods/{mod-id}/collections" }; 
        static const HttpRequestParams GetModCommentsRequest { Modio::Detail::Verb::GET, "/games/{game-id}/mods/{mod-id}/comments" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams AddModCommentRequest { Modio::Detail::Verb::POST, "/games/{game-id}/mods/{mod-id}/comments" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams DeleteModCommentRequest { Modio::Detail::Verb::DELETE, "/games/{game-id}/mods/{mod-id}/comments/{comment-id}" }; 
        static const HttpRequestParams GetModCommentRequest { Modio::Detail::Verb::GET, "/games/{game-id}/mods/{mod-id}/comments/{comment-id}" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams UpdateModCommentRequest { Modio::Detail::Verb::PUT, "/games/{game-id}/mods/{mod-id}/comments/{comment-id}" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams AddModCommentKarmaRequest { Modio::Detail::Verb::POST, "/games/{game-id}/mods/{mod-id}/comments/{comment-id}/karma" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams BrowseModfileCooksRequest { Modio::Detail::Verb::GET, "/games/{game-id}/mods/{mod-id}/cooks" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams UpsertModfileCooksRequest { Modio::Detail::Verb::POST, "/games/{game-id}/mods/{mod-id}/cooks" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams GetModDependantsRequest { Modio::Detail::Verb::GET, "/games/{game-id}/mods/{mod-id}/dependants" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams DeleteModDependenciesRequest { Modio::Detail::Verb::DELETE, "/games/{game-id}/mods/{mod-id}/dependencies" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams GetModDependenciesRequest { Modio::Detail::Verb::GET, "/games/{game-id}/mods/{mod-id}/dependencies" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams AddModDependenciesRequest { Modio::Detail::Verb::POST, "/games/{game-id}/mods/{mod-id}/dependencies" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams GetModEventsRequest { Modio::Detail::Verb::GET, "/games/{game-id}/mods/{mod-id}/events" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams GetModfilesRequest { Modio::Detail::Verb::GET, "/games/{game-id}/mods/{mod-id}/files" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams AddModfileRequest { Modio::Detail::Verb::POST, "/games/{game-id}/mods/{mod-id}/files" , GetContentTypeEnum("multipart/form-data") }; 
        static const HttpRequestParams DeleteMultipartUploadSessionRequest { Modio::Detail::Verb::DELETE, "/games/{game-id}/mods/{mod-id}/files/multipart" }; 
        static const HttpRequestParams GetMultipartUploadPartsRequest { Modio::Detail::Verb::GET, "/games/{game-id}/mods/{mod-id}/files/multipart" }; 
        static const HttpRequestParams CreateMultipartUploadSessionRequest { Modio::Detail::Verb::POST, "/games/{game-id}/mods/{mod-id}/files/multipart" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams AddMultipartUploadPartRequest { Modio::Detail::Verb::PUT, "/games/{game-id}/mods/{mod-id}/files/multipart" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams CompleteMultipartUploadSessionRequest { Modio::Detail::Verb::POST, "/games/{game-id}/mods/{mod-id}/files/multipart/complete" }; 
        static const HttpRequestParams GetMultipartUploadSessionsRequest { Modio::Detail::Verb::GET, "/games/{game-id}/mods/{mod-id}/files/multipart/sessions" }; 
        static const HttpRequestParams DeleteModfileRequest { Modio::Detail::Verb::DELETE, "/games/{game-id}/mods/{mod-id}/files/{file-id}" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams GetModfileRequest { Modio::Detail::Verb::GET, "/games/{game-id}/mods/{mod-id}/files/{file-id}" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams EditModfileRequest { Modio::Detail::Verb::PUT, "/games/{game-id}/mods/{mod-id}/files/{file-id}" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams ManagePlatformStatusRequest { Modio::Detail::Verb::POST, "/games/{game-id}/mods/{mod-id}/files/{file-id}/platforms" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams DeleteModMediaRequest { Modio::Detail::Verb::DELETE, "/games/{game-id}/mods/{mod-id}/media" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams AddModMediaRequest { Modio::Detail::Verb::POST, "/games/{game-id}/mods/{mod-id}/media" , GetContentTypeEnum("multipart/form-data") }; 
        static const HttpRequestParams ReorderModMediaRequest { Modio::Detail::Verb::PUT, "/games/{game-id}/mods/{mod-id}/media/reorder" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams DeleteModKvpMetadataRequest { Modio::Detail::Verb::DELETE, "/games/{game-id}/mods/{mod-id}/metadatakvp" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams GetModKvpMetadataRequest { Modio::Detail::Verb::GET, "/games/{game-id}/mods/{mod-id}/metadatakvp" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams AddModKvpMetadataRequest { Modio::Detail::Verb::POST, "/games/{game-id}/mods/{mod-id}/metadatakvp" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams GetUsersInModMonetizationTeamRequest { Modio::Detail::Verb::GET, "/games/{game-id}/mods/{mod-id}/monetization/team" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams CreateModMonetizationTeamRequest { Modio::Detail::Verb::POST, "/games/{game-id}/mods/{mod-id}/monetization/team" , GetContentTypeEnum("multipart/form-data") }; 
        static const HttpRequestParams AddModRatingRequest { Modio::Detail::Verb::POST, "/games/{game-id}/mods/{mod-id}/ratings" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams BrowseSourceModfilesRequest { Modio::Detail::Verb::GET, "/games/{game-id}/mods/{mod-id}/sources" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams AddSourceModfileRequest { Modio::Detail::Verb::POST, "/games/{game-id}/mods/{mod-id}/sources" , GetContentTypeEnum("multipart/form-data") }; 
        static const HttpRequestParams GetModStatsRequest { Modio::Detail::Verb::GET, "/games/{game-id}/mods/{mod-id}/stats" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams UnsubscribeFromModRequest { Modio::Detail::Verb::DELETE, "/games/{game-id}/mods/{mod-id}/subscribe" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams SubscribeToModRequest { Modio::Detail::Verb::POST, "/games/{game-id}/mods/{mod-id}/subscribe" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams DeleteModTagsRequest { Modio::Detail::Verb::DELETE, "/games/{game-id}/mods/{mod-id}/tags" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams GetModTagsRequest { Modio::Detail::Verb::GET, "/games/{game-id}/mods/{mod-id}/tags" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams AddModTagsRequest { Modio::Detail::Verb::POST, "/games/{game-id}/mods/{mod-id}/tags" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams GetModTeamMembersRequest { Modio::Detail::Verb::GET, "/games/{game-id}/mods/{mod-id}/team" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams AddModTeamMemberRequest { Modio::Detail::Verb::POST, "/games/{game-id}/mods/{mod-id}/team" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams DeleteModTeamMemberRequest { Modio::Detail::Verb::DELETE, "/games/{game-id}/mods/{mod-id}/team/{team-member-id}" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams UpdateModTeamMemberRequest { Modio::Detail::Verb::PUT, "/games/{game-id}/mods/{mod-id}/team/{team-member-id}" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams GetGameTokenPacksRequest { Modio::Detail::Verb::GET, "/games/{game-id}/monetization/token-packs" }; 
        static const HttpRequestParams GetGameStatsRequest { Modio::Detail::Verb::GET, "/games/{game-id}/stats" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams GetGameTagOptionsRequest { Modio::Detail::Verb::GET, "/games/{game-id}/tags" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams GetResourceOwnerRequest { Modio::Detail::Verb::POST, "/general/ownership" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams GetAuthenticatedUserRequest { Modio::Detail::Verb::GET, "/me" }; 
        static const HttpRequestParams GetMeCollectionsRequest { Modio::Detail::Verb::GET, "/me/collections" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams GetUserEntitlementsRequest { Modio::Detail::Verb::GET, "/me/entitlements" }; 
        static const HttpRequestParams GetUserEventsRequest { Modio::Detail::Verb::GET, "/me/events" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams GetUserModfilesRequest { Modio::Detail::Verb::GET, "/me/files" }; 
        static const HttpRequestParams MeGetFollowersRequest { Modio::Detail::Verb::GET, "/me/followers" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams GetUsersFollowingRequest { Modio::Detail::Verb::GET, "/me/following" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams GetMeFollowedCollectionsRequest { Modio::Detail::Verb::GET, "/me/following/collections" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams GetUserGamesRequest { Modio::Detail::Verb::GET, "/me/games" }; 
        static const HttpRequestParams SyncAppleEntitlementRequest { Modio::Detail::Verb::POST, "/me/iap/apple/sync" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams SyncGoogleEntitlementsRequest { Modio::Detail::Verb::POST, "/me/iap/google/sync" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams SyncMetaEntitlementRequest { Modio::Detail::Verb::POST, "/me/iap/meta/sync" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams SyncPlaystationNetworkEntitlementsRequest { Modio::Detail::Verb::POST, "/me/iap/psn/sync" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams SyncSteamEntitlementRequest { Modio::Detail::Verb::POST, "/me/iap/steam/sync" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams SyncXboxLiveEntitlementsRequest { Modio::Detail::Verb::POST, "/me/iap/xboxlive/sync" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams GetUserModsRequest { Modio::Detail::Verb::GET, "/me/mods" }; 
        static const HttpRequestParams GetUserPurchasesRequest { Modio::Detail::Verb::GET, "/me/purchased" }; 
        static const HttpRequestParams GetUserRatingsRequest { Modio::Detail::Verb::GET, "/me/ratings" }; 
        static const HttpRequestParams RequestUserDelegationTokenRequest { Modio::Detail::Verb::POST, "/me/s2s/oauth/token" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams GetUserSubscriptionsRequest { Modio::Detail::Verb::GET, "/me/subscribed" }; 
        static const HttpRequestParams GetUsersMutedRequest { Modio::Detail::Verb::GET, "/me/users/muted" }; 
        static const HttpRequestParams GetUserWalletRequest { Modio::Detail::Verb::GET, "/me/wallets" }; 
        static const HttpRequestParams MetricsSessionEndRequest { Modio::Detail::Verb::POST, "/metrics/sessions/end" , GetContentTypeEnum("application/json") }; 
        static const HttpRequestParams MetricsSessionHeartbeatRequest { Modio::Detail::Verb::POST, "/metrics/sessions/heartbeat" , GetContentTypeEnum("application/json") }; 
        static const HttpRequestParams MetricsSessionStartRequest { Modio::Detail::Verb::POST, "/metrics/sessions/start" , GetContentTypeEnum("application/json") }; 
        static const HttpRequestParams ExchangeEmailSecurityCodeRequest { Modio::Detail::Verb::POST, "/oauth/emailexchange" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams RequestEmailSecurityCodeRequest { Modio::Detail::Verb::POST, "/oauth/emailrequest" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams LogoutRequest { Modio::Detail::Verb::POST, "/oauth/logout" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams PingRequest { Modio::Detail::Verb::GET, "/ping" }; 
        static const HttpRequestParams SubmitReportRequest { Modio::Detail::Verb::POST, "/report" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams S2sDisconnectUserRequest { Modio::Detail::Verb::DELETE, "/s2s/connections/{portal-id}" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams GetMonetizationTransactionsRequest { Modio::Detail::Verb::GET, "/s2s/monetization-teams/{monetization-team-id}/transactions" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams GetMonetizationTransactionRequest { Modio::Detail::Verb::GET, "/s2s/monetization-teams/{monetization-team-id}/transactions/{transaction-id}" }; 
        static const HttpRequestParams S2sTransactionClawbackRequest { Modio::Detail::Verb::POST, "/s2s/transactions/clawback" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams S2sTransactionCommitRequest { Modio::Detail::Verb::POST, "/s2s/transactions/commit" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams S2sTransactionIntentRequest { Modio::Detail::Verb::POST, "/s2s/transactions/intent" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams GetUserPublicProfileRequest { Modio::Detail::Verb::GET, "/users/{user-id}" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams GetUserProfileCollectionsRequest { Modio::Detail::Verb::GET, "/users/{user-id}/collections" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams GetUserFollowersRequest { Modio::Detail::Verb::GET, "/users/{user-id}/followers" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams GetUserFollowingRequest { Modio::Detail::Verb::GET, "/users/{user-id}/following" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams FollowUserRequest { Modio::Detail::Verb::POST, "/users/{user-id}/following" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams UnfollowUserRequest { Modio::Detail::Verb::DELETE, "/users/{user-id}/following/{target-user-id}" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams UnmuteAUserRequest { Modio::Detail::Verb::DELETE, "/users/{user-id}/mute" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
        static const HttpRequestParams MuteAUserRequest { Modio::Detail::Verb::POST, "/users/{user-id}/mute" , GetContentTypeEnum("application/x-www-form-urlencoded") }; 
    }
}

MODIO_DISABLE_WARNING_POP
