/*
 *  Copyright (C) 2021 mod.io Pty Ltd. <https://mod.io>
 *
 *  This file is part of the mod.io SDK.
 *
 *  Distributed under the MIT License. (See accompanying file LICENSE or
 *   view online at <https://github.com/modio/modio-sdk/blob/main/LICENSE>)
 *
 */

#pragma once

#pragma push_macro("BLOCK_SIZE")
#undef BLOCK_SIZE

#include "modio/detail/ModioCompilerMacros.h"
MODIO_DISABLE_WARNING_PUSH
MODIO_DISABLE_WARNING_ASSIGNMENT_IMPLICITLY_DELETED
MODIO_DISABLE_WARNING_COPY_CONSTRUCTOR_IMPLICITLY_DELETED 
MODIO_DISABLE_WARNING_CPP98_COMPAT
MODIO_DISABLE_WARNING_SUGGEST_DESTRUCTOR_OVERRIDE
MODIO_DISABLE_WARNING_EXIT_TIME_DESTRUCTORS
MODIO_DISABLE_WARNING_MOVE_ASSIGNMENT_IMPLICITLY_DELETED
MODIO_DISABLE_WARNING_MOVE_CONSTRUCTOR_IMPLICITLY_DELETED
MODIO_DISABLE_WARNING_SPECTRE_MITIGATION
MODIO_DISABLE_WARNING_STRUCTURE_PADDING
MODIO_DISABLE_WARNING_UNSAFE_BUFFER_USAGE
MODIO_DISABLE_WARNING_UNUSED_FUNCTION
#include "concurrentqueue.h"
MODIO_DISABLE_WARNING_POP

#pragma pop_macro("BLOCK_SIZE")