FILTER_OP(Contains, "_q")
FILTER_OP(Equals, "")
FILTER_OP(Not, "-not")
FILTER_OP(Like,"-lk")
FILTER_OP(NotLike,"-not-lk")
FILTER_OP(In,"-in")
FILTER_OP(NotIn,"-not-in")
FILTER_OP(GreaterThan,"-min")
FILTER_OP(LessThan,"-max")
FILTER_OP(BitwiseAnd,"-bitwise-and")