== Getting started

=== Installation

[caption=FUTURE RELEASE] 
NOTE: CMake exported target and find_package support forthcoming

==== Inside a CMake project

. Clone the repository, or add as a submodule
. Ensure your project is using `cmake_minimum_required(VERSION 3.15)` or later
. `set (MODIO_PLATFORM WIN)` 
. `add_subdirectory(<sdk folder>)` 
. To use the header-only configuration:
+
[source,cmake]
----
target_compile_features(your_project PUBLIC cxx_std_17)
target_link_libraries(your_project PUBLIC modio)
---- 
. To use the static library configuration:
+
[source,cmake]
----
target_compile_features(your_project PUBLIC cxx_std_14)
target_link_libraries(your_project PUBLIC modioStatic) 
----


==== Standalone 
To make building the SDK easier, we provide a `CMakePresets.json` that will include the most common configurations as presets. 

|===
|Platform | Preset Name

|Windows | win64
|===

Debug presets have the `-debug` suffix, and Release-with-debug-info is `-dbginfo`, so if you want to build the SDK in debug configuration specify `win64-debug` as the preset name. 

To build the SDK using the default build and install directories:

. `cmake -S <path to sdk folder> --preset=Win64`
+ 
This will use the Ninja generator to create a Ninja build system in `<sdk folder>/out/build/win64`, which installs the compiled libraries etc to `<sdk folder>/out/install/win64`.
. `cmake --build <sdk folder>/out/build/win64`
+
This step compiles the SDK as a static library.
. `cmake --install out/win64/build`
+
This will produce a folder `<sdk folder>/out/install/win64` which contains the following:
+
* `header_only` - directory with the header-only version of the SDK
* `source` - directory containing the implementation files of the SDK for use in 'split compilation' mode
* `static` - directory containing the static library binaries and minimal public includes

===== Header-only mode

Simply add each of the subdirectories in `header_only` to your include directories and then `#include "modio/ModioSDK.h"`

===== Separate compilation mode

If you'd rather compile the implementation directly, simply add the cpp files in the `source` directory, and add the includes as per header-only mode. Define `MODIO_SEPARATE_COMPILATION`, and then `#include "modio/ModioSDK.h"`

===== Static library mode

Add the `inc` directory inside `static` to your includes and link against the static binary in the `lib` folder, defining `MODIO_SEPARATE_COMPILATION` and `#include "modio/ModioSDK.h"` as per separate compilation mode.


==== Other Build Systems

If you'd like to use another build system, or generate project files you can add to a larger Visual Studio solution, simply override the default generator when performing the first command above. For instance, to use a MSBuild-based Visual Studio Solution:

`cmake -S <path to sdk folder> --preset=Win64 -G"Visual Studio 16 2019"`

'''

=== Requirements

==== Platform Support

|===
|Platform | Supported? |Compiler

|Windows | ✔ | MSVC
|Windows (GDK) | ✔ (Contact us) | Vendor-provided
|OSX |2022 |
|Linux |Q4 2021 |
|Nintendo Switch | ✔ (Contact us) | Vendor-provided
|XBox (GDK) | ✔ (Contact us) | Vendor-provided

|===

==== Compiler Feature Support

|===
|Configuration | C++ Version

|Header-only| C++17
|Static Library | C++14
|===


'''

=== SDK structure and concepts

==== Flat API
The mod.io SDK has a fairly simple overall structure which primarily consists of a flat interface of free functions. These broadly have the following categories:

* SDK management (initialization, teardown, event loop)
* User authentication
* Mod browsing and querying
* Mod management (subscription, unsubscription)

==== Value objects
All data returned by the free functions is presented using a small set of classes, containing information such as:

* Details for mods that are available for installation
* Progress information about mods being installed
* Details, and load paths, for installed mods

These objects will be returned to you by the SDK by-value, so if you want to hold onto them once you've shut down the SDK you can do so, and unlike interfaces that return values via interface pointers you do not need to call `dispose`, `release` or some other management function when you are done with them.
This allows you, for instance, to initialize the SDK, query the installed mods, and retain that list even after shutting down the SDK again so you can stop running the SDK's event loop. 

==== UTF-8 guarantees

The SDK uses UTF8 for all strings, stored in `std::string`, as does the mod.io REST API. 

==== Thread-safety guarantees

[caption=CURRENT RELEASE] 
NOTE: The mod.io SDK is currently NOT thread-safe. All calls to SDK functions should be made on the same thread.

[caption=FUTURE RELEASE] 
NOTE: The mod.io SDK is thread-safe for all calls EXCEPT <<RunPendingHandlers>>. See <<Maintaining the SDK event loop>> below for further information. 

NOTE: The SDK event loop, any internal SDK event handlers, and all callbacks you provide to the mod.io SDK, will be run on the thread invoking <<RunPendingHandlers>>.

==== Non-blocking, asynchronous interface

The SDK communicates with the mod.io servers, the filesystem on the device you're using, and platform-provided services for authentication. All of these may not return results immediately, so a large number of the SDK's public methods are non-blocking and asynchronous.

NOTE: All async methods in the public API end with the suffix `Async`. 

===== Callback conventions
All of these asynchronous methods take a `std::function`-derived callback, which will be invoked exactly once with the results of the requested operation. 
Every async callback takes a <<ErrorCode>> as its first parameter, with any optional results wrapped in <<Optional>> so that you can easily check if a result is valid or not. 

Any return values provided to your callback are passed-by-value - the SDK doesn't expect you to have to call `release` or otherwise free up resources given to you. 

NOTE: Even if the SDK is shut down while asynchronous operations are in-flight, your callbacks will still be invoked *exactly once*. In this instance, the <<ErrorCode>> the callback receives will indicate a cancellation state, and you should check for this as part of your error handling in your callbacks.

===== Maintaining the SDK event loop

In order to provide a non-blocking implementation, the SDK operates an internal event loop. This event loop, will only ever run on the thread which calls <<RunPendingHandlers>>.

NOTE: This means that if you stop calling <<RunPendingHandlers>>, any pending asynchronous API methods you have called will not complete and their associated callbacks will not be invoked, nor will the internal data allocated for those operations be freed.

==== Users and Local Profiles

The mod.io SDK uses a Local Profile throughout it's lifetime. The Local Profile may optionally contain an authenticated user (if you have called any of the authentication functions). 

An authenticated user is required in order to install mods, and perform other operations. Check the `requires` section on any public SDK function to see what operations require an authenticated user. However, you can freely browse and search the available mods for your game and only prompt the user to authenticate/create an account when they wish to perform any of those restricted operations. 

To change a Local Profile's authenticated user, call <<ClearUserDataAsync>> to remove the authenticated user, and then re-authenticate as per normal. 

NOTE: This will remove the authenticated user from the local device. Any UGC they have installed will be uninstalled, if no other Local Profiles have authenticated users that are currently subscribed to it. 

If you'd like to simply switch which authenticated user is currently being used, without uninstalling, or add a new authenticated user to the local system, simply switch to another Local Profile by calling <<ShutdownAsync>> and then re-initializing via <<InitializeAsync>>, specifying a different Local Profile name in the initialization parameters you supply.

==== Error handling

Many functions in the SDK's public interface either return, or provide as the first parameter in a callback, a <<ErrorCode>> value. This is essentially a numeric error code with a category and an associated string message. 

The SDK doesn't attempt to predict what your error-handling logic or requirements are: instead, we return the error code to you so you can decide what to do. For instance, if you call a function and receive an error code `ec == Modio::HttpError::CannotOpenConnection`, do you want to close down the SDK? Retry again according to custom back-off logic? That decision is left to the consuming application. 

For more details on the error codes and how to inspect their values, please see <<SDK quick-start: Error Handling>> and <<ErrorCode>>.

==== Mod Data Directory

The plugin stores mods in a game-specific directory in the following directory by default:

|===
|Windows | Linux | OSX

|`${FolderID_Public}/mod.io` | TBD |TBD
|===

However, this value can be overridden in one of two ways:

* Globally for a system account
+
On first run of a game using the plugin, `${FOLDERID_LocalAppData}/mod.io/globalsettings.json` will be created. 
+
This JSON object contains a `RootLocalDataPath` element - changing the string here to a valid path on disk will globally redirect the mod installation directory for *ALL* games using the mod.io UE4 plugin or native SDK for the current system account. 
+
NOTE: Changing this value while the SDK is initialized is not supported and behaviour is undefined.

* Per-Local Profile override
+
Per-game, Local Profile-specific settings are stored in `${FOLDERID_LocalAppData}/mod.io/${GameId}/${Local Profile Name}/user.json`. 
+
*Adding* a `RootLocalDataPath` element to this file will redirect the mod installation directory for this specific game only, for the current Local Profile. Removing this value will cause the game to revert back to the global value in `globalsettings.json`.

'''

=== SDK quick-start: Initialization and Teardown

As mentioned in <<Maintaining the SDK event loop>>, the SDK's internal event loop requires care and attention in the form of <<RunPendingHandlers>>.
For best performance it should be called at least once per frame, so it should either go into your project's main loop or into a `tick`-style function on an appropriate controller/manager object. 

[source,cpp]
----
while(bGameIsRunning)
{
    Modio::RunPendingHandlers();
    //other stuff
}
----

When you are ready to initialize the SDK for the current user, you'll need to call <<InitializeAsync>>, passing in your product's mod.io ID, your API key, the Local Profile name, and a callback/handler so you know when the SDK is initialized correctly. 

[source,cpp]
----

//represents some external state so we know that the SDK is good to go - could be anything
Modio::Optional<bool> SDKInitialized;

Modio::InitializeOptions Options;
Options.APIKey = Modio::ApiKey(YOUR_API_KEY);
Options.GameEnvironment = Modio::Environment::Test;
Options.GameID = Modio::GameID(YOUR_GAME_ID);
Options.User = LocalProfileName;

Modio::InitializeAsync(Options, [&SDKInitialized](Modio::ErrorCode ec) {
    if (ec)
    {
        // SDK initialization failure
    }
    else
    {
        // SDK init OK - can now make other calls to the SDK, show mod browser UI, etc
    }
});


----

.Notes
* By convention you'll see these code examples pass in lambda functions as callback handlers, but you can use anything convertible to `std::function` with the appropriate signature. 
* The error-handling in this sample is deliberately kept brief. See <<SDK quick-start: Error Handling>> for more information on error handling. 
* You can perform calls to other functions, such as something that shows your mod browser UI implementation, directly in the callback. The primary caveat to doing much processing here is that you'll be running in the context of, and therefore blocking, the thread running the callback, which is the thread running <<RunPendingHandlers>>.


Doing the reverse and shutting down the SDK is equally simple:
[source, cpp]
----
//State variable, stored in some valid scope
bool SDKShutdownComplete = false;

//Capture reference to the state variable in the lambda - could use shared_ptr for more safety instead
Modio::ShutdownAsync([&SDKShutdownComplete](Modio::ErrorCode ec)
{
    SDKShutdownComplete = true;
});

while(!SDKShutdownComplete)
{
    Modio::RunPendingHandlers();
}

----

.Notes
* You will need to continue to call <<RunPendingHandlers>> while the async shutdown is in progress to allow for intermediate handlers to finish running.

'''

=== SDK quick-start: User Authentication

Mod.io provides two ways for users to create an account to use the service: email authentication, and single sign on (SSO) through an external authentication partner. The flow for these is slightly different.

==== Email authentication

Mod.io allows users to create an account on the mod.io website using an email address. Once the user has accepted the mod.io Terms of Use and created an account, they can use that email address to log in and access mod.io services in your game. 

Email authentication involves:
    1. Submitting the user's email address
    2. The user retrieving the one-time code mod.io sends to that address (externally to your application)
    3. Submitting the code provided by the user

[source, cpp]
----
Modio::RequestEmailAuthCodeAsync(Modio::EmailAddress(UserProvidedEmailAddress), [](Modio::ErrorCode ec)
{
    //Handle errors if ec is truthy
});

// some time later, after the user inputs their authentication code

Modio::AuthenticateUserEmailAsync(Modio::EmailAuthCode(UserProvidedAuthCode), [](Modio::ErrorCode ec) {
		if (ec)
		{
            //Authentication failure, inspect ec to determine what information to provide to the end user
		}
		else
		{   
            //User is now authenticated and able to manage their subscriptions via SDK calls
		}
	});

----

==== SSO/External authentication

Mod.io features single sign on authentication from a number of external providers. This currently includes:

    * Xbox Live
	* Steam
    * GoG
    * Itch
    * Switch
    * Discord

In order to use SSO with mod.io, a user must have accepted the mod.io Terms of Use in order to create an account. 

This means the external authentication flow is the following:

    1. Call <<AuthenticateUserExternalAsync>> , passing in any provider-specific parameters, setting `AuthenticationParams::bUserHasAcceptedTerms` to false, and indicating which authentication provider you wish to use
    2. Check the error code in the callback - if it indicates the user has not yet created an account or accepted the terms, call <<GetTermsOfUseAsync>> and display the provided information to your user
    3. If the user clicks the OK/affirmative button on your screen displaying the terms of use, repeat the call in step 1 but setting `AuthenticationParams::bUserHasAcceptedTerms` to *true*
    4. Check the error code in the callback - a false-y error code indicates that authentication was successful, and users can now install and manage mods and subscriptions.

[source, cpp]
----
UserParams.bUserHasAcceptedTerms = false;
Modio::AuthenticateUserExternalAsync(UserParams,Provider,[Provider, Language](Modio::ErrorCode ec)
{
    if (ec)
    {
        if (ec == Modio::ApiError::UserNoAcceptTermsOfUse)
        {
            //We need to display the terms of use to the user
            Modio::GetTermsOfUseAsync(Provider, Language, [](Modio::ErrorCode ec, Modio::Optional<Modio::Terms> Terms)
            {
                if (ec)
                {
                    //something went wrong fetching the terms, inspect ec to decide what to do
                }
                else
                {
                    //Display the terms of use to the user, remember not to block in the callback here!
                    NonBlockingFunctionThatDisplaysTheTermsOfUse(Terms);
                }
            });
        }
    }
});

//Later sometime, when your user clicks accept on the terms of use
UserParams.bUserHasAcceptedTerms = true;
Modio::AuthenticateUserExternalAsync(UserParams,Provider,[](Modio::ErrorCode ec){/* ... */});

----

'''

=== SDK quick-start: Browsing available mods

Now that you've followed the instructions in <<SDK quick-start: Initialization and Teardown>> you can begin to query the available mods for information you can display to your end users. The primary way this is done is through <<ListAllModsAsync>>.

[source,cpp]
----

Modio::ListAllModsAsync(Modio::FilterParams(), [](Modio::ErrorCode ec, Modio::Optional<Modio::ModInfoList> Results) 
{
    if (ec)
    {
        //Error handling
    }
    else
    {
        for (Modio::ModInfo& CurrentModProfile : *Results)
        {
            std::cout << CurrentModProfile.ProfileName;
        }
    }
});
----

You'll note that <<ListAllModsAsync>> takes a <<FilterParams>> object as its first parameter. The default state of this object is set to ask for the first 100 results (the maximum number returnable in a query), sorting by mod ID.

To search for a specific query string, sort in a different order, or combine different filters, you can pass in a FilterParams object like this:

[source,cpp]
----
//Search queries
Modio::ListAllModsAsync(Modio::FilterParams().NameContains("SomeString"), ...)
//Sorting
Modio::ListAllModsAsync(Modio::FilterParams().SortBy(Modio::FilterParams::SortFieldType::DownloadsToday, Modio::SortDirection::Ascending), ...)

//Ranged results - starting at index 20, return 10 results
Modio::ListAllModsAsync(Modio::FilterParams.NameContains("Your Query").IndexedResults(20, 10), ...)

//Ranged results - return the 20th page of 10 results
Modio::ListAllModsAsync(Modio::FilterParams.NameContains("Your Query").PagedResults(20, 10), ...)
----

'''

=== SDK quick-start: Mod subscriptions and management

So you've shown the user some mods based on a query they've submitted through your UI, and the user has picked one that they'd like to install. How do you begin the installation process, and once the mod is installed how do you know what files to be loading into memory?

==== Mod subscriptions

A user indicates that they want to have a mod installed by 'subscribing' to it. Subscriptions are stored on the mod.io servers and associated to a user's mod.io account. 

When a user 'unsubscribes' to a mod, they're indicating they'd like to have that mod uninstalled from any device they're logged in on. 

The API for managing subscriptions is simple and consists of a call to either <<SubscribeToModAsync>> or <<UnsubscribeFromModAsync>> with the ID of the mod in question and a callback to receive the status of the request:

[source,cpp]
----
//Subscription
Modio::SubscribeToModAsync(SomeModId, [](Modio::ErrorCode ec)
{
    if (ec)
    {
        //Didn't subscribe, show message to user
    }
    else
    {
        //Successfully subscribed on the server
    }
});

//Unsubscription
Modio::UnsubscribeFromModAsync(SomeModId, [](Modio::ErrorCode ec)
{
    if (ec)
    {
        //Couldn't unsub, show error 
    }
    else
    {
        //Server records unsubscription, mod won't be installed or available for this user any longer
    }
});

----

===== External subscription changes

Because the mod.io service is available as a website as well as integration within your applications, users can manage their subscriptions (and therefore installations) outside of your application. This means that we need to be able to query the server for any external subscription changes. To do this, you will need to use <<FetchExternalUpdatesAsync>> to synchronise the server state with the SDK's local subscriptions:

[source,cpp]
----
Modio::FetchExternalUpdatesAsync([](Modio::ErrorCode ec) {
    if (ec)
    {
        //Couldn't fetch external subscription data, handle error
    }
    {
        //Don't need to do anything here as such, the SDK's internal state has been synchronised 
    }
});
----

NOTE: You should call <<FetchExternalUpdatesAsync>> at particular times in your application when you want to ensure that the state is up-to-date - the SDK will apply rate-limiting internally if you try to call it too often.

===== Checking the user subscription list

In order to see which mods the user has subscribed to, call <<QueryUserSubscriptions>> to retrieve a collection of <<ModCollectionEntry>> objects, one for each subscribed mod. 
Each of these objects contains the mod's state, profile information, ID, and other data, suitable for showing users a list of their subscriptions.

NOTE: This collection includes mods that are still in the process of being installed! Make sure to check the result of <<ModCollectionEntry::GetModState>> before trying to load files from the mods in this collection, or alternatively use <<QueryUserInstallations>> as described in <<Retrieving mod directory paths for loading>>.


==== Installation management, mod paths

So a subscription marks a mod as requiring installation, and an unsubscription indicates uninstallation, but how do you actually control when the SDK *does* those things? After all, you don't want a mod to be uninstalled after your main program has loaded those files into memory, locking them from deletion. Likewise, you probably don't want to be using networking or processor resources during gameplay for downloading mods. In order to give you control over when these processes occur, without forcing you to shut down the SDK entirely, you can call <<EnableModManagement>> and <<DisableModManagement>>.

In order to display a notification to your users when a mod is finished installing or updating, <<EnableModManagement>> asks you to provide it with a callback. Because <<EnableModManagement>> is not an async function (ie it doesn't end with *Async), the callback operates differently to asynchronous result callbacks you use elsewhere in the SDK. A callback given to this function will be held by the SDK until a corresponding call to <<DisableModManagement>> or <<ShutdownAsync>>, and the callback will be invoked every time a mod is automatically installed, updated, or uninstalled by the SDK's internal event loop.

[source,cpp]
----
Modio::EnableModManagement([](Modio::ModManagementEvent ModEvent) {

    if (ModEvent.Status && ModEvent.Event == Modio::ModManagementEvent::EventType::Installed)
    {
        fmt::print("Mod with id {} failed to install : {}", ModEvent.ID, ModEvent.Status.message());
    }

});


//Some time later: check if there's a mod being installed, or more mods that require installation pending
if (!Modio::IsModManagementBusy())
{
    //This will reset any in-progress installations to pending, so we're only calling it if nothing's being processed
    Modio::DisableModManagement();
}
----

===== Retrieving mod directory paths for loading

So now we have the user picking mods and marking them for installation, we're enabling mod management at a point where we don't mind the SDK changing the filesystem, and mods are being installed by the SDK, we now need to know where they are on disk, otherwise you can't load them into your game!

The easiest way to do this is by using <<QueryUserInstallations>>. This function allows you to specify if you want to include outdated mods or not, and will return a collection of <<ModCollectionEntry>> objects that you can query for folder paths you can use to load files into your title. 

[source,cpp]
----
std::vector<Modio::filesystem::path> ModPaths;

//This will iterate over all the installed mods that are up-to-date
for (std::pair<Modio::ModID, Modio::ModCollectionEntry>& Entry : Modio::QueryUserInstallations())
{
    ModPaths.push_back(Entry.second().GetPath());
}

//You can now append whatever filenames you expect in a mod to the paths and load those in
for (Modio::filesystem::path& Path : ModPaths)
{
    YourGame::FileHandle ModManifest = YourGame::OpenFile(Path / "mod_manifest.txt");
}
----

'''

=== SDK quick-start: Error Handling

Many functions in the SDK, especially asynchronous functions either return a Modio::ErrorCode, or else invoke your passed-in callback with a Modio::ErrorCode as the first parameter.

==== Checking for errors

You can check if a Modio::ErrorCode represents a success or failure by checking its 'truthyness'. If an ErrorCode evaluates to true, then the function failed.

[source,cpp]
----
Modio::ErrorCode ec;
if (ec)
{
    //Error code was truthy, therefore an error occurred. 
}
else
{
    //Error code was false-y, therefore the operation succeeded
}
----

==== Inspecting ErrorCodes more deeply

Sometimes, this information will be all that is required, just a simple 'success/fail' that you can handle. 

In many cases, however, you will want to perform some degree of inspection on an ErrorCode in order to determine specific information about that error - if nothing else, so that you can display a reason for the failure to the end user.

===== Direct Queries

It's possible to query the raw value of an ErrorCode by comparing it against a particular enum value, for instance, to check if a particular ErrorCode represents a filesystem error of 'Not enough space', you could do the following:

[source,cpp]
----
if (ec == Modio::FilesystemError::InsufficientSpace)
{
    //Handle insufficient space by deleting some files, or something else
}
else
{
    //Other error handling here
}
----

Of course, this means you can chain such checks together:

[source,cpp]
----
if (ec == Modio::FilesystemError::InsufficientSpace)
{
    //Handle insufficient space by deleting some files, or something else
}
else if (ec == Modio::FilesystemError::NoPermission)
{
    //Handle permissions error by asking the user to re-run as admin, or prompt for elevation, or similar
}
else
{
    //Other error handling here
}
----

This isn't ideal though, for a number of reasons:

* It's quite verbose
* Doesn't check for semantic equivalency, only literal equivalency (some hypothetical other error that means the same thing, would return false because the codes don't match)
* Requires you to handle each individual case regardless of whether you need to or not
* Scales poorly if there are a number of error codes with equivalent semantics in this context

We can address these by using so-called 'semantic queries' against the error code rather than directly comparing numerical values. 

===== Semantic Queries
The SDK provides a function with a number of overloads that you can use to query for the semantic meaning of an ErrorCode.

Firstly, you can query if an ErrorCode is equivalent to a specific raw enum value:

[source,cpp]
----
Modio::ErrorCode ec;
if (Modio::ErrorCodeMatches(ec, Modio::HttpError::CannotOpenConnection))
{
    //We couldn't connect to the mod.io server
}
----

This of course can be chained together like the literal value comparison mentioned earlier:

[source,cpp]
----
Modio::ErrorCode ec;
if (Modio::ErrorCodeMatches(ec, Modio::HttpError::CannotOpenConnection))
{
    //We couldn't connect to the mod.io server
}
else if (Modio::ErrorCodeMatches(ec, Modio::HttpError::ServerClosedConnection))
{
    // Server unexpectedly closed the connection
}
----

This still requires, however, knowledge of the different types of HTTP errors. In your application, though, you probably don't actually need to handle them differently. The semantics of networking errors are largely 'try the function again later'.

This is where the second overload of <<ErrorCodeMatches>> comes in. 

It allows you to query if the error satisfies a particular condition, such as 'does this code represent some kind of networking error':

[source,cpp]
----
Modio::ErrorCode ec;
if (Modio::ErrorCodeMatches(ec, Modio::ErrorConditionTypes::NetworkError))
{
    //Error code represents some kind of network error 
}
else
{
    //Error code is not a network error
}
----

By querying if the error meets a specific condition, you can focus on handling a family of errors (in this case, network transmission errors) without needing to deal with individual errors within that grouping. No more manually checking against individual HttpError values, just a single query. 

As a second example, when you ask the SDK to retrieve information about a specific mod, that mod ID might be invalid, or possibly even the mod could be deleted. Both of these result in an error, which you could handle like the following:

[source,cpp]
----
// In Modio::GetModInfoAsync callback
if (Modio::ErrorCodeMatches(ec,Modio::ApiError::RequestedModNotFound))
{
    //The mod ID wasn't valid, we couldn't find it
}
else if (Modio::ErrorCodeMatches(ec, Modio::ApiError::RequestedModDeleted))
{
    //The mod ID used to be valid, but the mod was deleted
}
else
{
    // ...
}
----

However, you may not really care about the reasons the mod couldn't be looked up - just that the mod information couldn't be returned.

As a result, you can query if the error code matches the `EntityNotFoundError` condition:

[source,cpp]
----
// In Modio::GetModInfoAsync callback
if (Modio::ErrorCodeMatches(ec,Modio::ErrorConditionTypes::EntityNotFoundError))
{
    //For whatever reason, the mod couldn't be found. Handle appropriately.
}
----

By grouping these codes into semantic checks, it also helps you to potentially consolidate your error handling into a more limited set of generic error handlers rather than needing to deal with each potential outcome individually. 

==== Putting it all together

By combining queries against categories with queries against specific values, you can handle general families of errors at a single location with special-case clauses for a particular error as necessary:

[source,cpp]
----
Modio::GetModInfoAsync(SomeModId, [](Modio::ErrorCode ec, Modio::Optional<Modio::ModInfo> Info)
{
    if (ec)
    {
        if (Modio::ErrorCodeMatches(ec, Modio::ErrorConditionTypes::NetworkError)) // Does the code belong to the network error group?
        {
            //Error code represents some kind of network error, ask the user to try again later
        }
        else if (Modio::ErrorCodeMatches(ec, Modio::ErrorConditionTypes::EntityNotFoundError)) //Does the code belong to the 'not found' group?
        {
            //We couldn't find that mod for whatever reason, this means that the list you're fetching the mod ID from is probably stale
            //Call something here to fetch an updated version of the list from the server
        } 
        else if (Modio::ErrorCodeMatches(ec, Modio::GenericError::SDKNotInitialized)) // Is the code semantically equivalent to the specific error "SDK not initialized"?
        {
            //Your application is trying to call SDK functions without initializing the SDK first        
        }
    }
});

----

==== Parameter Validation Errors

Some of the SDK functions may return errors that indicate a parameter or data validation failure. For these cases, the SDK parses the error response from the mod.io API and stores the information about which parameters failed validation until the next network request is performed. If an SDK function returns an error which matches `Modio::ErrorConditionTypes::InvalidArgsError`, you can call <<GetLastValidationError>> in your callback to retrieve those errors and display appropriate feedback to the end user. 

'''

