:gitplant: http://www.plantuml.com/plantuml/proxy?src=https://raw.githubusercontent.com/modio/modio-sdk/main/doc/chapters/diagrams/general-overview/

== Getting started

=== Prerequisites

The following packages are required to build the mod.io SDK for Windows 10:

- Visual Studio 2019 (Community version works)
- Visual Studio 2019 "Desktop Development with C++" (via Visual Studio Installer)

These include the required CMake (version 3.20 or higher), Ninja, and MSVC C++ compiler.

=== Dependencies

The mod.io SDK has the following dependencies:

- https://github.com/stephenwhittle/asio[asio]
- https://github.com/gulrak/filesystem[filesystem]
- https://github.com/fmtlib/fmt[fmt]
- https://github.com/nekipelov/httpparser[httpparser]
- https://github.com/nlohmann/json[json]
- https://github.com/TartanLlama/optional[optional]
- https://github.com/nemtrif/utfcpp[utfcpp]
- https://github.com/ARMmbed/mbedtls[mbedtls] (linux)

While it is possible to download the SDK source code as a zip file from GitHub, a recursive clone will also download all dependencies. To ensure these dependencies are downloaded, use the following commands:

[source, zsh]
----
git clone --recurse-submodule https://github.com/modio/modio-sdk
cd modio-sdk
----

== Installation

The mod.io SDK can be installed using one of the following methods:

- Inside a CMake project
- Standalone: <<header-only>>
- Standalone: <<separate-compilation>>
- Standalone: <<static-library>>

=== Linux Dependencies

The mod.io SDK requires a Linux kernel with liburing support (v5.1 or later). The io_uring system calls provides asynchronous input/output operations. To fulfill that requirement and have the development tools ready, the following commands employ the "apt" package manager (tested on Ubuntu 20.04 Focal Fossa):

[source,bash]
----
sudo apt update
sudo apt upgrade
sudo apt install llvm clang lldb make wget python3 ninja-build git unzip
## Install Cmake
wget -q -O cmake-linux.sh https://github.com/Kitware/CMake/releases/download/v3.21.3/cmake-3.21.3-Linux-x86_64.sh
sh cmake-linux.sh -- --skip-license --prefix=/usr/
## Install liburing-dev
wget http://mirrors.kernel.org/ubuntu/pool/main/libu/liburing/liburing-dev_0.7-3ubuntu3_amd64.deb
wget http://mirrors.kernel.org/ubuntu/pool/main/libu/liburing/liburing1_0.7-3ubuntu3_amd64.deb
sudo apt install ./liburing*deb
----

=== macOS Dependencies

The mod.io SDK for development on macOS requires Clang 10 or GCC 10, which come included in the XCode 12 installation. To install CMake 3.20 or Ninja 1.10, it is recommended to use https://brew.sh[brew] as follows:

[source,bash]
----
brew install cmake ninja
----

=== Inside a CMake project

. Clone the repository, or add it as a submodule
. Add the following commands to a CMakeLists.txt file specific to your project
.. Confirm `your_project` uses CMake 3.20 or later
+
[source,cmake]
----
cmake_minimum_required(VERSION 3.20)
----
.. Specify the target platform, with options: WIN or LINUX
+
[source,cmake]
----
set (MODIO_PLATFORM WIN)
----
.. Add the SDK subdirectory to your project
+
[source,cmake]
----
add_subdirectory(<modio-sdk folder> EXCLUDE_FROM_ALL)
----
.. Link the library to your project
+
* To use the header-only configuration:
+
[source,cmake]
----
target_compile_features(your_project PUBLIC cxx_std_17)
target_link_libraries(your_project PUBLIC modio)
----
* Or to use the static library configuration:
+
[source,cmake]
----
target_compile_features(your_project PUBLIC cxx_std_14)
target_link_libraries(your_project PUBLIC modioStatic)
----

=== Standalone
To simplify the SDK compilation, the file `CMakePresets.json` includes the most common configurations as `presets` that employ Ninja by default. Therefore, confirm it is available on your `PATH` unless you want to <<override, override>> the CMake generator in use.

|===
|Platform | Preset          | Target       | Build System
|Windows  | win64           | Release      | Visual Studio 2019
|Windows  | win64-debug     | Debug        | Visual Studio 2019
|Windows  | win64-dbginfo   | Pre-Release  | Visual Studio 2019
|Linux    | linux64         | Release      | Ninja
|Linux    | linux64-debug   | Debug        | Ninja
|Linux    | linux64-dbginfo | Pre-Release  | Ninja
|macOS    | macOS           | Release      | Ninja or XCode
|macOS    | macOS-debug     | Debug        | Ninja or XCode
|macOS    | macOS-dbginfo   | Pre-Release  | Ninja or XCode
|===

Debug presets have the `-debug` suffix, and Release-with-debug-info is `-dbginfo`. For example, if you want to build the SDK in debug configuration specify `win64-debug` as the preset name.

To build the SDK using the default build and install directories:

. `cmake -S <modio-sdk folder> --preset=win64`
+
This will use the Ninja generator to create a Ninja build system in `<modio-sdk folder>/out/build/win64`. It installs the compiled libraries/headers to `<modio-sdk folder>/out/install/win64`.
. `cmake --build <modio-sdk folder>/out/build/win64`
+
This step compiles the SDK as a static library.
. `cmake --install <modio-sdk folder>/out/build/win64`
+
This produces a folder `<modio-sdk folder>/out/install/win64` with the following:
+
* `header_only` - directory with the header-only version of the SDK
* `source` - directory containing the implementation files of the SDK for use in 'split compilation' mode
* `static` - directory containing the static library binaries and necessary public include headers

==== Header-only mode [[header-only]]

Simply add each of the subdirectories in `header_only` to your include directories. Then, in `your_project` source file add `#include "modio/ModioSDK.h"`

==== Separate compilation mode [[separate-compilation]]

If you prefer to compile the source code directly, add the `cpp` files in the `source` directory, along with the `include` from the header-only mode.
You must add `MODIO_SEPARATE_COMPILATION` to your project's compiler definitions. Then, in `your_project` source file add `#include "modio/ModioSDK.h"`

==== Static library mode [[static-library]]

Add the `inc` directory inside `static` to your `include` and link against the static binary in the `lib` folder.  You must add `MODIO_SEPARATE_COMPILATION` to your project's compiler definitions. Then, in `your_project` source file add `#include "modio/ModioSDK.h"`

=== Other Build Systems [[override]]

If you use a different build system or wish to generate project files for inclusion in an existing Visual Studio solution, you can override the default CMake generator. For example, it is possible to use an MSBuild-based Visual Studio Solution:

```
cmake -S <modio-sdk folder> --preset=win64 -G "Visual Studio 16 2019"
cmake --build <modio-sdk folder>/out/install/win64
cmake --install <modio-sdk folder>/out/install/win64
```

'''

=== Requirements

==== Platform Support

|===
|Platform       | Support                       |Compiler
|Windows        | ✔                             | MSVC C++ 2019
|Windows (GDK)  | ✔ <<contact-us,(Contact Us)>> | Vendor-provided
|Nintendo Switch| ✔ <<contact-us,(Contact Us)>> | Vendor-provided
|XBox (GDK)     | ✔ <<contact-us,(Contact Us)>> | Vendor-provided
|Linux          | ✔                             | Clang 10
|macOS          | ✔                             | Clang 10
|===

==== Compiler Feature Support

|===
|Configuration  | Version
|Header-only    | C++17 (Windows)
|Static Library | C++14
|===

'''

=== SDK structure and concepts

The following diagram provides an overview of the mod.io SDK initialization procedure, its asynchronous nature.
image:{gitplant}modio_sdk_flow-init.puml[alt:"mod.io SDK Initialization flow"]

==== Flat API
The mod.io SDK has a simple structure that primarily consists of a flat interface. These broadly have the following categories:

* SDK management: Initialization, teardown, event loop
* User authentication
* Mod browsing and querying
* Mod management: subscribe, unsubscribe.

See <<quick-start>> for basic guides for each of these categories.

==== Value objects
All data returned by the SDK uses a small set of classes, containing information such as:

* Details for mods available for installation
* Status information about in-progress mod management operations
* Details and load paths for installed mods.

These objects return as `pass-by-value`. In other words, if you want to hold onto them once you've shut down the SDK you can do so. In contrast to interfaces that return values via interface pointers, all SDK objects do not need to call `dispose`, `release`, or some other memory manager when their scope finishes.

This flexibility allows you to initialize the SDK, query the installed mods, and keep that list. Then shut down the SDK and stop running the SDK's event loop.

==== UTF-8 guarantees

The SDK uses UTF8 for all strings, stored in `std::string`, as does the mod.io REST API.

==== Non-blocking, asynchronous interface

The SDK communicates with the mod.io servers, the filesystem on the device it is running on, and platform-specific authentication services. All of these may not return results immediately; therefore, a large number of the SDK's public methods are non-blocking and asynchronous.

NOTE: All asynchronous methods in the public API have the suffix `Async`.

===== Callback conventions
These asynchronous methods take a `std::function`-derived callback, which will be invoked exactly once with the results of the requested operation.

Every async callback takes an <<ErrorCode>> as its first parameter, with any results wrapped in <<Optional>> to check if a result is valid or empty.

Return values provided to your callback are passed `by-value`. The SDK does not expect you to have to call `release` or free up resources given to you.

NOTE: Even if the SDK shuts down while asynchronous operations are pending, the remaining callbacks will still execute *exactly once*. In this case, the callback receives an <<ErrorCode>> to indicate a canceled state. Your project should handle gracefully this behavior as part of your error handling.

===== Maintaining the SDK event loop

In order to provide a non-blocking implementation, the SDK operates an internal event loop. This event loop only runs on the thread which calls <<RunPendingHandlers>>.

The event loop, all internal event handlers and callbacks provided to the mod.io SDK execute on the thread invoking <<RunPendingHandlers>>. It is necessary to execute <<RunPendingHandlers>> on the same thread, otherwise, its behavior is undefined.

NOTE: If you stop calling <<RunPendingHandlers>>, any pending asynchronous API methods will not complete and their associated callbacks will not be invoked. It also includes the internal data allocated for those operations, as well as the release of any allocated objects.

==== Users and Local Profiles

The mod.io SDK uses a "Local Profile" throughout its lifetime. The Local Profile may optionally contain an authenticated user, once you have successfully authenticated using the appropriate SDK function.

An authenticated user is required to install mods and perform other operations. Check the `requires` section on any SDK function to see what operations need an authenticated user. However, anyone can freely browse and search your game's available mods and only prompt the user to authenticate/create an account when they wish to perform any restricted operations (such as rating or subscribing to a mod).

To change a Local Profile's authenticated user, call <<ClearUserDataAsync>> to remove the authenticated user, and then re-authenticate as normal.

NOTE: A call to <<ClearUserDataAsync>> removes the authenticated user from the local device. Any installed content is removed from local storage if no other Local Profiles contain authenticated users with active subscriptions to it.

To add a newly authenticated user or switch to one already-authenticated without removing the current one, swap to another Local Profile by calling <<ShutdownAsync>>, then re-initialize via <<InitializeAsync>> specifying a different Local Profile name in the initialization parameters you supply.

==== Error handling

Callback functions in the SDK either return a value or provide an <<ErrorCode>> value. It is a numeric error code with a category and an associated string message.

The SDK doesn't attempt to predict what your error-handling logic or requirements are. For example, if you call a function and receive an error code `ec == Modio::HttpError::CannotOpenConnection`, your application could potentially handle this by shutting down the SDK. Another application, however, might wish to retry after an interval determined by its own internal logic. As a result, the SDK defers to your application to decide how to handle errors for the functions you call.

For more details on the error codes and how to inspect their values, please see <<SDK quick-start: Error Handling>> and <<ErrorCode>>.

==== Mod Data Directory

The plugin stores mods in a game-specific directory in the following path by default:

|===
| Windows                    | Linux                    | OSX
|`${FolderID_Public}/mod.io` | `${USER_HOME}/mod.io`    | `${USER_HOME}/Library/Application Support/mod.io`
|===

NOTE: In Linux and macOS, mods and data binds to a single user. Every other client would have their own instance in their home directory.

However, this value can be overridden in one of two ways:

* Globally for a system account
+
On the first run of a game using the plugin, `${FolderID_LocalAppData}/mod.io/globalsettings.json` will be created.
+
This JSON object contains a `RootLocalDataPath` element. A change to this string to a valid path on disk will globally redirect the mod installation directory for *ALL* games using the mod.io SDK for the current system account (it also includes the Unreal Engine 4 plugin).
+
NOTE: Changing this value while the SDK is initialized is not supported and behavior is undefined.
+
NOTE: Consider that the mod.io SDK configuration folder is different from that where mod metadata and files stored.

* Per-Local Profile override
+
Per-game, Local Profile-specific settings are stored in `${FolderID_LocalAppData}/mod.io/${Game_ID}/${Local_Profile_Name}/user.json`.
+
*Adding* a `RootLocalDataPath` element to this file will redirect the mod installation directory for this specific game only, for the current Local Profile. Removing this value will cause the game to revert back to the global value in `globalsettings.json`.

'''
=== SDK quick-start [[quick-start]]

The following guides are provided to help you through the basic functions of the SDK as described in <<SDK structure and concepts>>.

* <<SDK quick-start: Initialization and Teardown>>
* <<SDK quick-start: User Authentication>>
* <<SDK quick-start: Browsing available mods>>
* <<SDK quick-start: Mod management and subscriptions>>
* <<SDK quick-start: Error Handling>>

'''
=== SDK quick-start: Initialization and Teardown

As mentioned in <<Maintaining the SDK event loop>>, the SDK's internal event loop requires care and attention in the form of <<RunPendingHandlers>>.

For optimal execution, <<RunPendingHandlers>> should be called at least once per frame. It could be located into your project's main loop or into a `tick`-style function on an appropriate controller/manager object.

[source,cpp]
----
while(bGameIsRunning == true)
{
    //other stuff
   Modio::RunPendingHandlers();
    //other stuff
}
----

When you are ready to initialize the SDK for the current user, you'll need to call <<InitializeAsync>>, passing in your product's mod.io ID, your API key, the Local Profile name, and a callback/handler so you know when the SDK is initialized correctly.  Note that <<InitializeAsync>>'s callback will be invoked after calling <<RunPendingHandlers>> from your project's main loop.

[source,cpp]
----
//represents some external state so we know that the SDK is good to go
Modio::Optional<bool> SDKInitialized;

Modio::InitializeOptions Options;
Options.APIKey = Modio::ApiKey(YOUR_API_KEY);
Options.GameID = Modio::GameID(YOUR_GAME_ID);
Options.User = "LocalProfileName";
Options.PortalInUse = Modio::Portal::None;
Options.GameEnvironment = Modio::Environment::Test;

Modio::InitializeAsync(Options, [&SDKInitialized](Modio::ErrorCode ec) {
    if (ec)
    {
        // SDK initialization failure
    }
    else
    {
        // SDK init OK - can now make other calls to the SDK, show mod browser UI, etc
    }
});
----

.Notes
* By convention you'll see these code examples pass in lambda functions as callback handlers, but you can use anything convertible to `std::function` with the appropriate signature.
* The error-handling in this sample is deliberately kept brief. See <<SDK quick-start: Error Handling>> for more information on error handling.
* You can perform calls to other functions, such as something that shows your mod browser UI implementation, directly in the callback. The primary caveat to doing much processing here is that you'll be running in the context of, and therefore blocking, the thread running the callback, which is the thread running <<RunPendingHandlers>>.


Doing the reverse and shutting down the SDK is equally simple:
[source, cpp]
----
//State variable, stored in some valid scope
bool SDKShutdownComplete = false;

//Capture reference to the state variable in the lambda - could use shared_ptr for more safety instead
Modio::ShutdownAsync([&SDKShutdownComplete](Modio::ErrorCode ec)
{
    SDKShutdownComplete = true;
});

while(!SDKShutdownComplete)
{
    Modio::RunPendingHandlers();
}

----

.Notes
* You will need to continue to call <<RunPendingHandlers>> while the async shutdown is in progress to allow for intermediate handlers to finish running.

'''

=== SDK quick-start: User Authentication

Mod.io provides two ways for users to create an account to use the service: email authentication and single sign on (SSO) through an external authentication partner. The flow for these is slightly different.

==== Email authentication

Mod.io allows users to create an account on the mod.io website using an email address. Once the user has accepted the mod.io Terms of Use and created an account, they can use that email address to log in and access mod.io services in your game.

Email authentication involves:
    1. Submitting the user's email address
    2. The user retrieving the one-time code mod.io sends to that address (externally to your application)
    3. Submitting the code provided by the user

[source, cpp]
----
Modio::RequestEmailAuthCodeAsync(Modio::EmailAddress(UserProvidedEmailAddress), [](Modio::ErrorCode ec)
{
    //Handle errors if ec is truthy
});

// some time later, after the user inputs their authentication code

Modio::AuthenticateUserEmailAsync(Modio::EmailAuthCode(UserProvidedAuthCode), [](Modio::ErrorCode ec) {
		if (ec)
		{
            //Authentication failure, inspect ec to determine what information to provide to the end user
		}
		else
		{
            //User is now authenticated and able to manage their subscriptions via SDK calls
		}
	});

----

==== SSO/External authentication

Mod.io features single sign on authentication from a number of external providers. This currently includes:

    * Xbox Live
	* Steam
    * GoG
    * Itch
    * Switch
    * Discord

In order to use SSO with mod.io, a user must have accepted the mod.io Terms of Use in order to create an account.

This means the external authentication flow is the following:

    1. Call <<AuthenticateUserExternalAsync>> , passing in any provider-specific parameters, setting `AuthenticationParams::bUserHasAcceptedTerms` to false, and indicating which authentication provider you wish to use
    2. Check the error code in the callback - if it indicates the user has not yet created an account or accepted the terms, call <<GetTermsOfUseAsync>> and display the provided information to your user
    3. If the user clicks the OK/affirmative button on your screen displaying the terms of use, repeat the call in step 1 but setting `AuthenticationParams::bUserHasAcceptedTerms` to *true*
    4. Check the error code in the callback - a false-y error code indicates that authentication was successful, and users can now install and manage mods and subscriptions.

[source, cpp]
----
Modio::AuthenticationParams UserParams;
UserParams.AuthToken = "AuthenticationToken";
UserParams.UserEmail = "UserEmail";
UserParams.bUserHasAcceptedTerms = false;

Modio::AuthenticateUserExternalAsync(UserParams,Provider,[Provider, Language](Modio::ErrorCode ec)
{
    if (ec)
    {
        if (ec == Modio::ApiError::UserNoAcceptTermsOfUse)
        {
            //We need to display the terms of use to the user
            Modio::GetTermsOfUseAsync(Provider, Language, [](Modio::ErrorCode ec, Modio::Optional<Modio::Terms> Terms)
            {
                if (ec)
                {
                    //something went wrong fetching the terms, inspect ec to decide what to do
                }
                else
                {
                    //Display the terms of use to the user, remember not to block in the callback here!
                    NonBlockingFunctionThatDisplaysTheTermsOfUse(Terms);
                }
            });
        }
    }
});

//Later sometime, when your user clicks accept on the terms of use
UserParams.bUserHasAcceptedTerms = true;
Modio::AuthenticateUserExternalAsync(UserParams,Provider,[](Modio::ErrorCode ec){/* ... */});

----

'''

=== SDK quick-start: Browsing available mods

Now that you've followed the instructions in <<SDK quick-start: Initialization and Teardown>> you can begin to query the available mods for information you can display to your end users. The primary way this is done is through <<ListAllModsAsync>>.

[source,cpp]
----

Modio::ListAllModsAsync(Modio::FilterParams(), [](Modio::ErrorCode ec, Modio::Optional<Modio::ModInfoList> Results)
{
    if (ec)
    {
        //Error handling
    }
    else
    {
        for (Modio::ModInfo& CurrentModProfile : *Results)
        {
            std::cout << CurrentModProfile.ProfileName;
        }
    }
});
----

You'll note that <<ListAllModsAsync>> takes a <<FilterParams>> object as its first parameter. The default state of this object is set to ask for the first 100 results (the maximum number returnable in a query), sorting by mod ID.

To search for a specific query string, sort in a different order, or combine different filters, you can pass in a FilterParams object like this:

[source,cpp]
----
//Search queries
Modio::ListAllModsAsync(Modio::FilterParams().NameContains("SomeString"), ...)
//Sorting
Modio::ListAllModsAsync(Modio::FilterParams().SortBy(Modio::FilterParams::SortFieldType::DownloadsToday, Modio::SortDirection::Ascending), ...)

//Ranged results - starting at index 20, return 10 results
Modio::ListAllModsAsync(Modio::FilterParams.NameContains("Your Query").IndexedResults(20, 10), ...)

//Ranged results - return the 20th page of 10 results
Modio::ListAllModsAsync(Modio::FilterParams.NameContains("Your Query").PagedResults(20, 10), ...)
----

'''

=== SDK quick-start: Mod management and subscriptions

So you've shown the user some mods based on a query they've submitted through your UI. The user has picked one that they'd like to install. This section explains how to trigger an installation process and the files downloaded to the filesystem.

==== Installation management and mod filepaths

A subscription marks a mod as requiring installation, whereas an unsubscription indicates uninstallation. But, how do you actually control when the SDK *does* those things? After all, you don't want a mod to be uninstalled after your main program has loaded those files into memory, locking them from deletion. Likewise, you probably don't want to be using networking or processor resources during gameplay for downloading mods. In order to give you control over when these processes occur, without forcing you to shut down the SDK entirely, you can call <<EnableModManagement>> and <<DisableModManagement>>.

In order to display a notification to your users when a mod is finished installing or updating, <<EnableModManagement>> asks you to provide a callback. Because <<EnableModManagement>> is *not an async* function (ie it doesn't end with *Async), the function handler operates differently compared to other asynchronous results callbacks you use elsewhere in the SDK. A handler given to this function will be held by the SDK until a corresponding call to <<DisableModManagement>> or <<ShutdownAsync>> takes place. The handler will be invoked every time a mod is automatically installed, updated, or uninstalled by the SDK's internal event loop.

[source,cpp]
----
Modio::EnableModManagement([](Modio::ModManagementEvent ModEvent)
{
    if (ModEvent.Status && ModEvent.Event == Modio::ModManagementEvent::EventType::Installed)
    {
        std::cout << "Mod with ID: << ModEvent.ID << " is installed" << std::endl;
    }
    else {
        std::cout << "Mod with ID: << ModEvent.ID << " failed to install: " << ModEvent.Status.message() << std::endl;
    }
});

//////////
//Sometime later: check if there's a mod being installed, or more mods that require installation pending
if (!Modio::IsModManagementBusy())
{
    //This will reset any in-progress installations to pending, so we're only calling it if nothing's being processed
    Modio::DisableModManagement();
}

----

==== Mod subscriptions

A user indicates they want to have a mod installed by 'subscribing' to it. The mod.io servers stores subscriptions and associates them with a particular user's mod.io account. When a user 'unsubscribes' to a mod, they indicate that mod should be uninstalled from any device they're logged in on.

The API for managing subscriptions is simple and consists of a call to either <<SubscribeToModAsync>> or <<UnsubscribeFromModAsync>> with the ID of the mod in question and a callback to receive the status of the request:

NOTE: In order to subscribe to a mod, it is necessary to call <<EnableModManagement>> beforehand.

[source,cpp]
----
//Subscription
Modio::SubscribeToModAsync(ModID, [](Modio::ErrorCode ec)
{
    if (ec)
    {
        //Didn't subscribe, show a message to the user
    }
    else
    {
        //Successfully subscribed on the server
    }
});

//Unsubscription
Modio::UnsubscribeFromModAsync(ModID, [](Modio::ErrorCode ec)
{
    if (ec)
    {
        //Couldn't unsubscribe, show error
    }
    else
    {
        //Server records unsubscription to remove the user's association to this mod
    }
});

----

===== External subscription changes

Remember that the mod.io service is available as a website besides the integration within your application. Users can manage their subscriptions (and therefore installations) outside of your game. Consequently, you must query the server for any external subscription changes. To do this, you will use <<FetchExternalUpdatesAsync>> to synchronise the server state with the SDK's local subscriptions:

[source,cpp]
----
Modio::FetchExternalUpdatesAsync([](Modio::ErrorCode ec)
{
    if (ec)
    {
        //Couldn't fetch external subscription data, handle error
    }
    {
        //The SDK's internal state synchronised. This is an acknowledgment of success
    }
});
----

NOTE: You should call <<FetchExternalUpdatesAsync>> at particular times in your application when you want to ensure that the state is up-to-date. The mod.io SDK will apply rate-limiting internally if you try to call it too often.

===== Checking the user subscription list

In order to see which mods the user has subscribed to, call <<QueryUserSubscriptions>> to retrieve a collection of <<ModCollectionEntry>> objects, one for each subscribed mod.
Each of these objects contains the mod's state, profile information, ID, and other data suitable for showing users a list of their subscriptions.

NOTE: This collection includes mods that are still in the process of being installed. Make sure to check the result of <<ModCollectionEntry::GetModState>> before trying to load files from the mods in this collection. Alternatively, use <<QueryUserInstallations>> as described in <<Retrieving mod directory paths for loading>>.

===== Retrieving mod directory filepaths for loading

Once the user can pick mods and subscribe to them (mark them for installation), mod.io SDK management can change the filesystem and retrieve mods. We now need to know where they are on the filesystem to load them into your gameplay.

The easiest way to do this is by using <<QueryUserInstallations>>. This function allows you to specify if you want to include outdated mods or not. It returns a collection of <<ModCollectionEntry>> objects that you can query for folder paths you can use to load files into your title.

[source,cpp]
----
std::vector<Modio::filesystem::path> ModPaths;

//It iterates over all the installed mods that are up-to-date
bool bIncludeOutdatedMods = false;
for (std::pair<Modio::ModID, Modio::ModCollectionEntry>& Entry : Modio::QueryUserInstallations(bIncludeOutdatedMods))
{
    ModPaths.push_back(Entry.second().GetPath());
}

//You can now append whatever filenames you expect in a mod to the paths and load those in
for (Modio::filesystem::path& Path : ModPaths)
{
    YourGame::FileHandle ModManifest = YourGame::OpenFile(Path / "mod_manifest.txt");
}
----

'''

=== SDK quick-start: Error Handling

Mayority of mod.io SDK functions return a Modio::ErrorCode. In particular, asynchronous callbacks execute with a Modio::ErrorCode as the first parameter.

==== Checking for errors

You can check if a Modio::ErrorCode represents a success or failure by checking its 'truthyness'. If an ErrorCode evaluates to true, then the function failed.

[source,cpp]
----
Modio::ErrorCode ec;
if (ec)
{
    //Error code was truthy, therefore an error occurred.
}
else
{
    //Error code was false-y, therefore the operation succeeded
}
----

==== Inspecting ErrorCodes more deeply

Sometimes, this information will be all that is required, just a simple 'success/fail' that you can handle.

In many cases, however, you will want to perform some degree of inspection on an ErrorCode to determine specific information about that error. If nothing else you can display a reason for the failure to the end user.

===== Direct Queries

It's possible to query the raw value of an ErrorCode by comparing it against a particular enum value, for instance, to check if a particular ErrorCode represents a filesystem error of 'Not enough space', you could do the following:

[source,cpp]
----
if (ec == Modio::FilesystemError::InsufficientSpace)
{
    //Handle insufficient space by possibly deleting some files.
}
else
{
    //Other error handling here
}
----

Of course, this means you can chain such checks together:

[source,cpp]
----
if (ec == Modio::FilesystemError::InsufficientSpace)
{
    //Handle insufficient space by possibly deleting some files.
}
else if (ec == Modio::FilesystemError::NoPermission)
{
    //Handle permissions error by asking the user to re-run as admin, or prompt for priviledge elevation.
}
else
{
    //Other error handling here
}
----

This isn't ideal though, here are some reasons:
* It's considerably verbose
* Doesn't check for semantic equivalency, only literal equivalency. In other words, some other error that derive from a similar issues, would return false because the codes don't match
* It requires you to handle each case regardless of whether you need to or not
* Scales poorly if there are several error codes with equivalent semantics in this context.

We can address these by using so-called 'semantic queries' against the error code rather than directly comparing numerical values.

===== Semantic Queries
The SDK provides a function with several overloads that you can use to query for the semantic meaning of an ErrorCode.

Firstly, you can query if an ErrorCode is equivalent to a specific raw enum value:

[source,cpp]
----
Modio::ErrorCode ec;
if (Modio::ErrorCodeMatches(ec, Modio::HttpError::CannotOpenConnection))
{
    //We couldn't connect to the mod.io server
}
----

This of course can be chained together like the literal value comparison mentioned earlier:

[source,cpp]
----
Modio::ErrorCode ec;
if (Modio::ErrorCodeMatches(ec, Modio::HttpError::CannotOpenConnection))
{
    //We couldn't connect to the mod.io server
}
else if (Modio::ErrorCodeMatches(ec, Modio::HttpError::ServerClosedConnection))
{
    //Server unexpectedly closed the connection
}
----

This still requires, however, knowledge of the different types of HTTP errors. In your application, though, you probably don't need to handle them differently. The semantics of networking errors are largely 'try the function again later'.

This is where the second overload of <<ErrorCodeMatches>> comes in. It allows you to query if the error satisfies a particular condition, such as 'does this code represent some kind of networking error':

[source,cpp]
----
Modio::ErrorCode ec;
if (Modio::ErrorCodeMatches(ec, Modio::ErrorConditionTypes::NetworkError))
{
    //Error code represents some kind of network error
}
else
{
    //Error code is not a network error
}
----

By querying if the error meets a specific condition, you can focus on handling a family of errors (in this case, network transmission errors) without needing to deal with individual errors within that group. No more manually checking against individual HttpError values, just a single query.

As a second example, when you ask the SDK to retrieve information about a specific mod, that ModID might be invalid, or possibly even deleted. Both of these result in an error, which you could handle like the following:

[source,cpp]
----
// Inside a Modio::GetModInfoAsync callback
if (Modio::ErrorCodeMatches(ec, Modio::ApiError::RequestedModNotFound))
{
    //The ModID wasn't valid, we couldn't find it
}
else if (Modio::ErrorCodeMatches(ec, Modio::ApiError::RequestedModDeleted))
{
    //The ModID used to be valid, but the mod was deleted
}
else
{
    // Some other error...
}
----

However, you may not care about the reasons the mod couldn't be retrieved just that the mod information did not return a valid object.

As a result, you can query if the error code matches the `EntityNotFoundError` condition:

[source,cpp]
----
// In Modio::GetModInfoAsync callback
if (Modio::ErrorCodeMatches(ec, Modio::ErrorConditionTypes::EntityNotFoundError))
{
    //The mod couldn't be found. Handle appropriately.
}
----

By grouping these codes into semantic checks, it also helps you to potentially consolidate your error handling into a more limited set of generic error handlers rather than needing to deal with each potential outcome individually.

==== Putting it all together

By combining queries of categories with queries of specific values, you can handle general families of errors at a single location with special-case clauses for a particular error as necessary:

[source,cpp]
----
Modio::GetModInfoAsync(ModID, [](Modio::ErrorCode ec, Modio::Optional<Modio::ModInfo> Info)
{
    if (ec)
    {
        if (Modio::ErrorCodeMatches(ec, Modio::ErrorConditionTypes::NetworkError)) // NetworkError group
        {
            //Error code represents some network error kind. Possibly ask the user to try again later.
        }
        else if (Modio::ErrorCodeMatches(ec, Modio::ErrorConditionTypes::EntityNotFoundError)) //Entity Not Found group
        {
            //An mod entity is not located with this configuration. Therefore, the list you're fetching the ModID from is probably stale. A remedy could be to fetch an updated version of the list from the server.
        }
        else if (Modio::ErrorCodeMatches(ec, Modio::GenericError::SDKNotInitialized)) // SDK not initialized group
        {
            //Your application is trying to call SDK functions without initializing the SDK first
        }
    }
});

----

==== Parameter Validation Errors

Some of the SDK functions may return errors that indicate a parameter or data validation failure. For these cases, the SDK parses the error response from the mod.io API and stores the information about which parameters failed validation until the next network request executes. If an SDK function returns an error which matches `Modio::ErrorConditionTypes::InvalidArgsError`, you can call <<GetLastValidationError>> in your callback to retrieve those errors and display appropriate feedback to the end-user.

'''
