== mod.io Linux SDK Integration

The use of Linux with the mod.io SDK is ready by default. You can find the `linux`` directory in the platform subdirectory of your SDK installation.
You can then target `LINUX` to compile the mod.io SDK for Linux SDK.

== Linux SDK Versions

The mod.io SDK is built and tested against Ubuntu 21.04 using clang v10. Using different versions of the Linux SDK may result in compilation issues.

In Linux, the default way to compile the mod.io SDK requires CMake with Ninja as generator, which you can install following the https://cmake.org/download/[CMake webpage] instructions or using a package manager like `apt`:

[source,cmake]
----
sudo apt install cmake ninja
----

=== Inside a CMake project

. Unzip the archive
. Confirm `your_project` uses CMake 3.20 or later

[source,cmake]
----
cmake_minimum_required(VERSION 3.20)
----
. Specify the target platform with ORBIS
+
[source,cmake]
----
set (MODIO_PLATFORM LINUX)
----
. Add the SDK subdirectory to your project
+
[source,cmake]
----
add_subdirectory(<modio-sdk folder> EXCLUDE_FROM_ALL)
target_compile_features(your_project PUBLIC cxx_std_17)
----
. Link the library to your project
+
* To use the header-only configuration:
+
[source,cmake]
----
target_link_libraries(your_project PUBLIC modio)
----
* Or to use the static library configuration:
+
[source,cmake]
----
target_link_libraries(your_project PUBLIC modioStatic)
----

To simplify the CMake configuration, the folder `cmake/` has the file `CMakePresets.json` with the basic configuration required to guide the mod.io SDK compilation using the Linux SDK. If you copy that file to the folder root, it can be used as follows:

[source,cmake]
----
cmake --preset win
----

== Backend environment

If you wish to use a different mod.io backend environment than the default `LIVE` environment (possibly `TEST`), please specify this as the `MODIO_DEFAULT_SERVER` parameter during the `cmake configuration` step. Similarly, you can add this variable to your `CMakePresets.json` file as follows:

[source,json]
----
...
"cacheVariables": 
{
    "MODIO_DEFAULT_SERVER": 
    {
    "type": "STRING",
    "value": "LIVE"
    },
}
...
----

For more details, follow the general details described in the https://github.com/modio/modio-sdk[mod.io repository]
